/**
* CRL 快速开发框架 V3.1
* Copyright (c) 2016 Hubro All rights reserved.
* GitHub https://github.com/hubro-xx/CRL3
* 主页 http://www.cnblogs.com/hubro
* 在线文档 http://crl.changqidongli.com/
*/
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Mvc.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Mvc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=[charset]&quot; /&gt;
        ///&lt;title&gt;网页出错了&lt;/title&gt;
        ///&lt;link rel=&quot;stylesheet&quot; href=&quot;/content/error.css&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div class=&quot;error&quot;&gt;
        ///  &lt;ul&gt;
        ///    &lt;li&gt;
        ///      &lt;h1&gt;程序产生一些异常,无法继续浏览,请刷新或重试&lt;/h1&gt;
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///      &lt;h2&gt;异常描述：[ERRO_TITLE]&lt;/h2&gt;
        ///    &lt;/li&gt;
        ///    &lt;li&gt;
        ///      &lt;h3&gt;错误代码： [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string erro {
            get {
                return ResourceManager.GetString("erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;script src=&quot;/Scripts/jquery-1.8.2.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///    function add() {
        ///        var str = &apos;&lt;input name=&quot;uploadpic&quot; type=&quot;file&quot; /&gt;&apos;;
        ///        $(&quot;#divAppend&quot;).append(&quot;&quot;, str);
        ///    }
        ///&lt;/script&gt;
        ///&lt;form action=&quot;/handler/UploadImage&quot; method=&quot;post&quot; enctype=&quot;multipart/form-data&quot;&gt;
        ///    &lt;div id=&quot;divAppend&quot;&gt;&lt;input name=&quot;uploadpic&quot; type=&quot;file&quot; accept=&quot;.jpg,.jpeg,.gif,.bmp,.png&quot; /&gt;&lt;/div&gt;
        ///    &lt;input id=&quot;folder&quot; name=&quot;folder&quot; type=&quot;hidden&quot; value=&quot;product&quot; /&gt;
        ///    &lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
    }
}
